---
server:
    timezone: 'UTC'
    locale: 'en_US.UTF-8'
    hostname: 'project_demo.vagrant'
    packages:
        - curl
        - wget
        - python-software-properties
        - mc
        - htop
        - git

nginx:
    docroot: '/var/www/project/web'
    index: 'app_dev.php'
    servername: 'project_demo.vagrant'

php:
    repo: 'ppa:ondrej/php'
    packages:
      - php7.0-dev
      - php7.0-cli
      - php7.0-intl
      - php7.0-mcrypt
      - php7.0-curl
      - php7.0-gd
      - php7.0-imap
      - php7.0-mysql
      - php7.0-xml
      - php7.0-mbstring
      - php7.0-bcmath
      - php7.0-zip

xdebug:
    install: true
    version: '2.4.1'
    dest: '2.4.1'

composer:
    install: false

symfony:
    cacheclear: true
    assetsdump: true
    assetsinstall: true
    migrations: true
    moveparams: false
    composerinstall: false
    projectroot: '/var/www/project'
    console_dest: 'bin/console'
    parameter_file: 'parameters.yml.vagrant.dist'
    tmp: '/tmp/project'
    env:
        cache: 'SYMFONY__KERNEL__CACHE_DIR="/tmp/project/cache"'
        logs: 'SYMFONY__KERNEL__LOGS_DIR="/tmp/project/logs"'
    nginx_params: 'fastcgi_param SYMFONY__KERNEL__CACHE_DIR "/tmp/project/cache";fastcgi_param SYMFONY__KERNEL__LOGS_DIR "/tmp/project/logs";'

mysql:
    install: true
    root_password: 'root'
    database: 'project_demo'
    user: 'project'
    password: 'project'
    dump: 'db.sql'
    packages:
        - mysql-server
        - mysql-client
        - python-mysqldb

mongodb:
    install: false

redis:
    install: false
    port: 6379

rabbitmq:
    install: false
    user: 'user'
    password: 'password'
    plugins: [rabbitmq_management]

elasticsearch:
    install: false
    port: 9200
    version: 1.5.2