---
- name: optimize Symfony realpath_cache_size
  lineinfile: dest=/etc/php/7.0/fpm/php.ini
              regexp=';?realpath_cache_size ='
              line='realpath_cache_size = 4096k'

- name: optimize Symfony realpath_cache_ttl
  lineinfile: dest=/etc/php/7.0/fpm/php.ini
              regexp=';?realpath_cache_ttl ='
              line='realpath_cache_ttl = 7200'
  notify:
      - restart php7.0-fpm