---
- hosts: all
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - server
    - server_host
    - nginx
    - php
    - {role: "mysql", when: mysql.install }
    - {role: "xdebug", when: xdebug.install }
    - {role: "composer", when: composer.install }
    - {role: "mongodb", when: mongodb.install }
    - {role: "redis", when: redis.install }
    - {role: "rabbitmq", when: rabbitmq.install }
    - {role: "elasticsearch", when: elasticsearch.install }